// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(evtTopic TopicEvent, msgTopic TopicMessage, userMessage string) (Event, error) {
	message := NewMessage(msgTopic, userMessage)
	event, err := NewEvent(evtTopic, message)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
